services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
            cache_from:
                - qrcode-artistic-frontend:latest
            cache_to:
                - type=inline
            args:
                - NEXT_PUBLIC_API_URL=https://qraft.shauryaa.dev
        container_name: qrcode-artistic-frontend
        environment:
            - PORT=3000
            - HOST=0.0.0.0
            - NEXT_PUBLIC_API_URL=https://qraft.shauryaa.dev
        ports:
            - "127.0.0.1:3000:3000"
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
